#!/usr/bin/env node
/**
 * Generate caddy/Caddyfile from config/domains.json.
 * Adding a domain then means editing ONE file (domains.json) and re-running this.
 *
 *   node scripts/gen-caddy.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const config = JSON.parse(readFileSync(root + 'config/domains.json', 'utf8'));

const blocks = config.domains.map((d) => `${d.domain}, www.${d.domain} {
	import common
	root * /srv/www/${d.domain}
	file_server
	log {
		output file /var/log/caddy/${d.domain}.log {
			roll_size 10mb
			roll_keep 5
		}
	}
}`).join('\n\n');

const caddyfile = `# =============================================================================
# AUTO-GENERATED by scripts/gen-caddy.mjs — do not edit by hand.
# Add domains in config/domains.json, then: node scripts/gen-caddy.mjs
#
# Cloudflare SSL/TLS mode MUST be "Full (strict)".
#   Flexible -> ERR_TOO_MANY_REDIRECTS (redirect loop)
#   Full(strict) -> correct; Caddy serves a real Let's Encrypt cert
# =============================================================================

{
	email ${config.email.forwardTo}
}

(common) {
	encode zstd gzip
	header {
		Strict-Transport-Security "max-age=31536000; includeSubDomains"
		X-Content-Type-Options "nosniff"
		Referrer-Policy "strict-origin-when-cross-origin"
		X-Frame-Options "SAMEORIGIN"
		-Server
	}
	@assets path /_astro/*
	header @assets Cache-Control "public, max-age=31536000, immutable"
	handle_errors {
		respond "{err.status_code} {err.status_text}" {err.status_code}
	}
}

${blocks}
`;

writeFileSync(root + 'caddy/Caddyfile', caddyfile);
console.log(`Wrote caddy/Caddyfile for ${config.domains.length} domain(s): ${config.domains.map((d) => d.domain).join(', ')}`);
